version: 2.1

jobs:
  build_and_push:
    docker:
      - image: circleci/python:3.7  # You can use a different image as needed
    steps:
      - checkout  # Check out the source code

      - setup_remote_docker:
          docker_layer_caching: true  # Enable caching to speed up builds

      - run:
          name: Build Docker images
          command: |
            docker build -t reverseproxy ./udagram-reverseproxy
            docker build -t udagram-api-user ./udagram-api-user
            docker build -t udagram-api-feed ./udagram-api-feed
            docker build -t udagram-frontend ./udagram-frontend

      - run:
          name: Tag Docker images
          command: |
            docker tag reverseproxy $DOCKER_USERNAME/udagram-reverseproxy:v1
            docker tag udagram-api-user $DOCKER_USERNAME/udagram-api-user:v1
            docker tag udagram-api-feed $DOCKER_USERNAME/udagram-api-feed:v1
            docker tag udagram-frontend $DOCKER_USERNAME/udagram-frontend:v1

      - run:
          name: Log in to DockerHub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - run:
          name: Push Docker images
          command: |
            docker push $DOCKER_USERNAME/udagram-reverseproxy:v1
            docker push $DOCKER_USERNAME/udagram-api-user:v1
            docker push $DOCKER_USERNAME/udagram-api-feed:v1
            docker push $DOCKER_USERNAME/udagram-frontend:v1

workflows:
  version: 2
  build_and_push_images:
    jobs:
      - build_and_push
