apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  aws_access_key_id: QUtJQVo3TzZRN0U2QjRXNjVNTzY=
  aws_secret_access_key: Wk91aTZIVUJlMm1nd082WWZ4R1V0VExuRjErZEhrcnI4UTBFWGlCcQ==
